### ISSUE TITLE
reliability of stats

### ISSUE THREAD

**Issue by UrielPaluch** [tbuscaglia/datos.futbol#10]
Analizar la confiabilidad de los datos. 

Mirar un partido y tomar notas propias. Luego compararlo con las de la aplicación.

El objetivo es poder ver la confiabilidad de las estadísticas.

**Comment by tbuscaglia** [comment]
Al indagar sobre el origen de las estadísticas usadas por [Fbref](https://fbref.com/en/) encontré las dos fuentes de datos que usa la pagina:

1. Las estadísticas avanzadas las saca de [Statsbomb](https://statsbomb.com/)
2. Las estadísticas generales (hora de partido, estadio, etc.) las consigue de [DataSportsGroup](https://datasportsgroup.com/coverage/soccer/)

**Comment by UrielPaluch** [comment]
Revisar **brevemente** las API's de [Statsbomb](https://statsbomb.com/) y [DataSportsGroup](https://datasportsgroup.com/coverage/soccer/) con el objetivo de ver si son mas completas que [Fbref](https://fbref.com/en/)
