### ISSUE TITLE
Investigar posibles fuentes de información

### ISSUE THREAD

**Issue by UrielPaluch** [tbuscaglia/datos.futbol#7]
Investigar y documentar dentro del issue APIs que sirvan para obtener la información. El análisis debe contener los campos que son posible obtener con cada API y la frecuencia de actualización de la data.

**Comment by tbuscaglia** [comment]
### API
La información será extraída de la pagina de estadísticas futbolísticas [fbref](https://fbref.com/en/) usando un paquete llamado [worldfootballR](https://github.com/JaseZiv/worldfootballR). Este paquete tiene [varias funciones](https://jaseziv.github.io/worldfootballR/articles/extract-fbref-data.html#player-match-logs-1) para extraer distintos tipos de datos. 

### Datos disponibles:

Las estadísticas disponibles de los jugadores para un partido son amplias. Un ejemplo se puede ver en [este](https://fbref.com/en/matches/4e263347/West-Ham-United-Newcastle-United-February-19-2022-Premier-League) resumen de partido.
