### ISSUE TITLE
Leer los métodos de la librería worldfootballR

### ISSUE THREAD

**Issue by UrielPaluch** [tbuscaglia/datos.futbol#9]
El objetivo es conocer los métodos que tiene la librería e investigar en detalle algún método en particular que resalte.

https://github.com/JaseZiv/worldfootballR

**Comment by tbuscaglia** [comment]
El método que trae la información que estamos buscando seria la función `get_advanced_match_stats( )`. Esta función trae las estadísticas de los jugadores para uno o varios partidos. Las estadísticas están divididas por tipo de acción. Son las siguientes:
- summary
- passing
- passing_types
- defense
- possession
- misc
- keeper

Cada una de estas categorías trae un df de estadísticas relacionadas a esa área para cada jugador del partido seleccionado.

**Comment by tbuscaglia** [comment]
@UrielPaluch
